language: cpp


jobs:
  include:
    - os: linux
      dist: bionic
      compiler: clang
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: focal
      compiler: clang
    - os: linux
      dist: focal
      compiler: gcc
    - os: osx
      osx_image: xcode11.3
      compiler: clang
    - os: osx
      osx_image: xcode11.3
      compiler: gcc
      

addons:
  apt:
    packages:
      - cmake
      - qt5-default
      - libqt5opengl5-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libprotobuf-dev 
      - protobuf-compiler 
      - libode-dev
      - libboost-dev
  homebrew:
    taps: robotology/formulae
    packages:
      - qt5
      - protobuf
      - robotology/formulae/ode

script:
  # grsim
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
